# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freshman_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sophomore_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('junior_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('senior_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
