# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='freshman_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='junior_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='senior_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='sophomore_score',
            field=models.IntegerField(),
        ),
    ]
