# Generated by Django 3.0.8 on 2020-07-15 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreBoard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("freshman_score", models.IntegerField()),
                ("sophomore_score", models.IntegerField()),
                ("junior_score", models.IntegerField()),
                ("senior_score", models.IntegerField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.Event"
                    ),
                ),
            ],
        ),
    ]
