# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160924_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=4096),
        ),
    ]
