# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20160930_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=48000),
        ),
    ]
