# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20160930_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Location', max_length=512),
            preserve_default=False,
        ),
    ]
