# Generated by Django 3.1.13 on 2023-09-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_auto_20230901_1648"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_hoco_admin",
            field=models.BooleanField(default=False),
        ),
    ]
